List<String> randomResponses = [
  ///when high % responses
  'There’s nothing to it. It’s dead easy.',
  'Nothing to worry about. It’s a cinch.',
  'Anyone can do it. It’s not rocket science.',
  'It’s so easy to do – it’s child’s play.',
  'It’s a walk in the park.',
  'It’s a doddle.',
  'It’s a breeze.',
  'It’s as easy as a,b,c.',
  'You could do it with your eyes shut !',
  'You could do it in your sleep !',
  'I could do that blindfold!',
  'I could do that standing still !',
  'I could do it with one hand tied behind my back !',
  'It’s a piece of cake.',
  'It’s as easy as pie.',
  'It’s easier than drinking water through a straw !',

  ///when low % responses
  'It’s not as easy as it looks.',
  'It’s quite difficult actually.',
  'It’s quite tricky.',
  'The training course is fairly demanding.',
  'The job is not for the faint-hearted.',
  'It requires a bit of experience.',
  'It’s not for the inexperienced.',
  'It can be quite daunting for some people.',
  'It looks easy but some find it quite challenging.',
  'It may look straightforward but it’s tricky to get it right.',
  'It’s not a walk in the park by any means !',
  'You need to keep your wits about you while you’re doing it.',
  'It can be a nightmarish experience for some.',
  'It’s not easy. In fact it’s often an uphill battle all the way.',
  'It can be quite tough.',
  'It’s quite complicated.',
  'It can be tough at times.',
];
